services:
  mcu-site:
    image: ghcr.io/youssefprodev/mcu-site:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcu-site.rule=Host(`mcu.youssefprodev.com`)"
      - "traefik.http.routers.mcu-site.entrypoints=websecure"
      - "traefik.http.routers.mcu-site.tls=true"
      - "traefik.http.routers.mcu-site.tls.certresolver=cloudflare"
      - "traefik.http.services.mcu-site.loadbalancer.server.port=8000"

    environment:
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
    networks:
      - traefik
  media:
    image: nginx:alpine
    volumes:
      - ./media:/usr/share/nginx/html/media:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`mcu.youssefprodev.com`) && PathPrefix(`/media`)"
      - "traefik.http.routers.media.entrypoints=websecure"
      - "traefik.http.routers.media.tls=true"
      - "traefik.http.routers.media.tls.certresolver=cloudflare"
      - "traefik.http.services.media.loadbalancer.server.port=80"


networks:
  traefik:
    external: true