services:
  mcu-site:
    image: ghcr.io/youssefprodev/mcu-site:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcu-site.rule=Host(`mcu.youssefprodev.com`)"
      - "traefik.http.routers.mcu-site.entrypoints=websecure"
      - "traefik.http.routers.mcu-site.tls=true"
      - "traefik.http.routers.mcu-site.tls.certresolver=cloudflare"
      - "traefik.http.services.mcu-site.loadbalancer.server.port=8000"
    networks:
      - traefik
  command: > 
    sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mcu_site.wsgi:application --bind 0.0.0.0:8000"



networks:
  traefik:
    external: true