services:
  traefik:
    image: traefik:v3.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=false"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    networks:
      - traefik
  mcu-site:
    build:
      context: .
    image: mcu-site
    container_name: mcu-site
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcu-site.rule=Host(`mcu.localhost`)"
      - "traefik.http.routers.mcu-site.entrypoints=web"
      - "traefik.http.services.mcu-site.loadbalancer.server.port=8000"

    networks:
      - traefik
  media:
    image: nginx:alpine
    volumes:
      - ./media:/usr/share/nginx/html/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=PathPrefix(`/media`)"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.services.media.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
