version: "3.8"
services:
  traefik:
    image: traefik:v3.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    networks:
      - traefik

  mcu-site:
    build:
      context: .
    image: mcu-site
    container_name: mcu-site
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcu-site.rule=(Host(`mcu.localhost`) && !PathPrefix(`/media`))"
      - "traefik.http.routers.mcu-site.entrypoints=web"
      - "traefik.http.services.mcu-site.loadbalancer.server.port=8000"
    volumes:
      - media:/app/media # monta la cartella media anche qui, se necessario
    networks:
      - traefik
    depends_on:
      - traefik
  media:
    image: nginx:alpine
    container_name: mcu-site-media

    volumes:
      - media:/usr/share/nginx/html/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=(Host(`mcu.localhost`) && PathPrefix(`/media`))"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.services.media.loadbalancer.server.port=80"
    networks:
      - traefik
    depends_on:
      - traefik
      - mcu-site

networks:
  traefik:
    external: true
volumes:
  media:
    external: true
