# Generated by Django 4.2 on 2023-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggi',
            name='attore',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
