# Generated by Django 4.2 on 2023-04-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0002_personaggi_attore'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggi',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
