# Generated by Django 4.2 on 2023-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0003_personaggi_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
