# Generated by Django 4.2 on 2023-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0004_alter_personaggi_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggi',
            name='descrizione',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaggi',
            name='poteri',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
