# Generated by Django 4.2 on 2023-04-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0005_personaggi_descrizione_personaggi_poteri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaggi',
            old_name='poteri',
            new_name='abilita',
        ),
    ]
