# Generated by Django 4.2 on 2023-04-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0006_rename_poteri_personaggi_abilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggi',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
