# Generated by Django 4.2 on 2023-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0007_personaggi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/personaggi/'),
        ),
    ]
