# Generated by Django 4.2 on 2023-05-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0008_alter_personaggi_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaggi',
            options={'verbose_name_plural': 'Personaggi'},
        ),
    ]
