# Generated by Django 4.2 on 2023-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0009_alter_personaggi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='abilita',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='descrizione',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/personaggi/'),
        ),
    ]
