# Generated by Django 4.2 on 2023-05-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0010_alter_personaggi_abilita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='abilita',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='attore',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='descrizione',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='nome',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaggi',
            name='sopranome',
            field=models.TextField(max_length=100),
        ),
    ]
