# Generated by Django 4.2 on 2023-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0011_alter_personaggi_abilita_alter_personaggi_attore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='img',
            field=models.ImageField(blank=True, default='image/notfound.jpg', null=True, upload_to='image/personaggi/'),
        ),
    ]
