# Generated by Django 4.2 on 2023-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0012_alter_personaggi_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='img',
            field=models.ImageField(default='image/notfound.jpg', null=True, upload_to='image/personaggi/'),
        ),
    ]
