# Generated by Django 4.2 on 2023-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0014_alter_personaggi_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggi',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
