# Generated by Django 4.2 on 2023-04-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0004_alter_personaggi_img'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sopranome',
        ),
        migrations.AddField(
            model_name='home',
            name='personaggi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggi'),
        ),
    ]
