# Generated by Django 4.2 on 2023-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0008_alter_personaggi_img'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='protagonisti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggi'),
        ),
    ]
