# Generated by Django 4.2 on 2023-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_alter_productions_protagonisti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productions',
            options={'verbose_name_plural': 'Productions'},
        ),
        migrations.AddField(
            model_name='productions',
            name='uscita',
            field=models.DateField(null=True),
        ),
    ]
