# Generated by Django 4.2 on 2023-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_alter_productions_options_productions_uscita'),
    ]

    operations = [
        migrations.AddField(
            model_name='productions',
            name='fase',
            field=models.CharField(choices=[('F1', 'Fase 1'), ('F2', 'Fase 2'), ('F3', 'Fase 3'), ('F4', 'Fase 4')], default='---Fase---', max_length=2),
        ),
    ]
