# Generated by Django 4.2 on 2023-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0009_alter_personaggi_options'),
        ('productions', '0004_productions_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='fase',
            field=models.CharField(choices=[('Fase 1', 'Fase 1'), ('Fase 2', 'Fase 2'), ('Fase 3', 'Fase 3'), ('Fase 4', 'Fase 4'), ('Fase 5', 'Fase 5')], default=('Fase 5', 'Fase 5'), max_length=10),
        ),
        migrations.RemoveField(
            model_name='productions',
            name='protagonisti',
        ),
        migrations.AddField(
            model_name='productions',
            name='protagonisti',
            field=models.ManyToManyField(to='personaggi.personaggi'),
        ),
    ]
