# Generated by Django 4.2 on 2023-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0010_alter_personaggi_abilita_and_more'),
        ('productions', '0005_alter_productions_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productions',
            name='img',
            field=models.ImageField(blank=True, default='mcu_site/static/img/notfound.jpg', null=True, upload_to='media/image/productions/'),
        ),
        migrations.AlterField(
            model_name='productions',
            name='protagonisti',
            field=models.ManyToManyField(related_name='protagonisti', to='personaggi.personaggi'),
        ),
    ]
