# Generated by Django 4.2 on 2023-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_productions_img_alter_productions_protagonisti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='img',
            field=models.ImageField(blank=True, default='media/image/notfound.jpg', null=True, upload_to='media/image/productions/'),
        ),
    ]
