# Generated by Django 4.2 on 2023-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0007_alter_productions_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='img',
            field=models.ImageField(blank=True, default='image/notfound.jpg', null=True, upload_to='image/productions/'),
        ),
    ]
