# Generated by Django 4.2 on 2023-05-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0008_alter_productions_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='descrizione',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productions',
            name='nome',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productions',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
