# Generated by Django 4.2 on 2023-05-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_alter_productions_descrizione_alter_productions_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productions',
            options={'ordering': ['uscita'], 'verbose_name_plural': 'Productions'},
        ),
    ]
