# Generated by Django 4.2 on 2023-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0014_alter_personaggi_img'),
        ('productions', '0010_alter_productions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='protagonisti',
            field=models.ManyToManyField(related_name='RFilm', related_query_name='RFilm', to='personaggi.personaggi'),
        ),
    ]
